### ISSUE TITLE
Stack pointer nil in mirror cmd

### ISSUE THREAD

**Issue by harshavardhana** [minio/mc#1032]
~~~
goroutine 1 [semacquire]:
runtime.gopark(0x97f140, 0xaf5160, 0x8cdc40, 0xa, 0x19, 0x4)
	/usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc8200533e8 sp=0xc8200533c0
runtime.goparkunlock(0xaf5160, 0x8cdc40, 0xa, 0x45fb19, 0x4)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc820053420 sp=0xc8200533e8
runtime.semacquire(0xc82011feac, 0x4d3e01)
	/usr/local/go/src/runtime/sema.go:100 +0x2f7 fp=0xc820053480 sp=0xc820053420
sync.runtime_Semacquire(0xc82011feac)
	/usr/local/go/src/runtime/sema.go:43 +0x26 fp=0xc820053498 sp=0xc820053480
sync.(*WaitGroup).Wait(0xc82011fea0)
	/usr/local/go/src/sync/waitgroup.go:126 +0xb4 fp=0xc8200534e0 sp=0xc820053498
main.doMirrorCmdSession(0xc8200f3d70)
	/home/harsha/mygo/src/github.com/minio/mc/mirror-main.go:267 +0x59c fp=0xc820053618 sp=0xc8200534e0
main.mainMirror(0xc8200d24b0)
	/home/harsha/mygo/src/github.com/minio/mc/mirror-main.go:292 +0x46e fp=0xc8200537d0 sp=0xc820053618
github.com/minio/mc/vendor/github.com/minio/cli.Command.Run(0x8bd7a0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x94f6c0, 0x42, 0x0, ...)
	/home/harsha/mygo/src/github.com/minio/mc/vendor/github.com/minio/cli/command.go:123 +0x10be fp=0xc820053c88 sp=0xc8200537d0
github.com/minio/mc/vendor/github.com/minio/cli.(*App).Run(0xc82009c300, 0xc82000a230, 0x5, 0x5, 0x0, 0x0)
	/home/harsha/mygo/src/github.com/minio/mc/vendor/github.com/minio/cli/app.go:199 +0x77d fp=0xc820053ee8 sp=0xc820053c88
github.com/minio/mc/vendor/github.com/minio/cli.(*App).RunAndExitOnError(0xc82009c300)
	/home/harsha/mygo/src/github.com/minio/mc/vendor/github.com/minio/cli/app.go:210 +0x45 fp=0xc820053f30 sp=0xc820053ee8
main.main()
	/home/harsha/mygo/src/github.com/minio/mc/main.go:169 +0x65 fp=0xc820053f50 sp=0xc820053f30
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820053fa0 sp=0xc820053f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820053fa8 sp=0xc820053fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820040fb8 sp=0xc820040fb0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x97f140, 0xaee960, 0x8c9640, 0xf, 0x14, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc82002c758 sp=0xc82002c730
runtime.goparkunlock(0xaee960, 0x8c9640, 0xf, 0xc820000114, 0x1)
	/usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82002c790 sp=0xc82002c758
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:152 +0xb8 fp=0xc82002c7c0 sp=0xc82002c790
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002c7c8 sp=0xc82002c7c0
created by runtime.init.4
	/usr/local/go/src/runtime/proc.go:141 +0x2b

goroutine 3 [GC sweep wait]:
runtime.gopark(0x97f140, 0xaeeb20, 0x8c3450, 0xd, 0x485614, 0x1)
	/usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc82002cf48
~~~

**Comment by harshavardhana** [comment]
https://github.com/golang/go/commit/05a3b1fce56a95e40512bae9f62656098f198834 - looks like an issue with golang 1.5 release

**Comment by harshavardhana** [comment]
https://github.com/golang/go/issues/12253 - relevant bug

**Comment by harshavardhana** [comment]
Relevant part from error stack

```
goroutine 897 [copystack]:
runtime.assertE2T2(0x787700, 0x787700, 0xc820496910, 0xc8203579e8, 0x1)
                             /usr/local/go/src/runtime/iface.go:233 fp=0xc82050d940 sp=0xc82050d938
github.com/minio/mc/vendor/github.com/minio/minio/pkg/quick.(*config).Load(0xc82022e7e0, 0xc82022e7a0, 0x1c, 0x0)
                                                                                         /home/harsha/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio/pkg/quick/quick.go:192 +0x485 fp=0xc82050da30 sp=0xc82050d940
main.getMcConfig(0xc8201a54f0, 0xc8203e6618)
                               /home/harsha/mygo/src/github.com/minio/mc/config.go:129 +0x225 fp=0xc82050dab0 sp=0xc82050da30
main.getHostConfig(0xc8201a54f0, 0xf, 0x0, 0x0, 0x0, 0x0, 0xc820705468)
                                 /home/harsha/mygo/src/github.com/minio/mc/hostconfig.go:33 +0x49 fp=0xc82050dc00 sp=0xc82050dab0
main.url2Client(0xc8201a54f0, 0xf, 0x0, 0x0, 0xc820705510)
                              /home/harsha/mygo/src/github.com/minio/mc/common-methods.go:204 +0x10d fp=0xc82050dcb0 sp=0xc82050dc00
main.source2Client(0xc8201a54f0, 0xf, 0x0, 0x0, 0xc820144900)
                                 /home/harsha/mygo/src/github.com/minio/mc/common-methods.go:219 +0x3b fp=0xc82050dd10 sp=0xc82050dcb0
main.getSource(0xc8201a54f0, 0xf, 0x0, 0x0, 0xc82044d270, 0xc82022e640)
                             /home/harsha/mygo/src/github.com/minio/mc/common-methods.go:57 +0x3d fp=0xc82050dd60 sp=0xc82050dd10
main.doMirror(0xc8204cf600, 0xc82056f5a0, 0x1, 0x4, 0x0, 0xc8204cb900, 0xc8200e9f10, 0xc8204cb980, 0xc820144a20)
                            /home/harsha/mygo/src/github.com/minio/mc/mirror-main.go:103 +0x285 fp=0xc82050df48 sp=0xc82050dd60
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82050df50 sp=0xc82050df48
created by main.doMirrorCmdSession.func2
        /home/harsha/mygo/src/github.com/minio/mc/mirror-main.go:299 +0x3d0

```

**Comment by harshavardhana** [comment]
With Golang 1.5.1 release this issue is closed, re-open if seen again.
