### ISSUE TITLE
pipe: Runtime out of memory error when uploading a large file - using 'mc pipe'

### ISSUE THREAD

**Issue by yoavlt** [minio/mc#1641]
Hi.

I'm trying to upload big data to Amazon S3, but it failed because runtime out of memory error. The following is error message.

$ cat movie.mp4 | mc pipe awsdisk/target/file_path.mp4

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x9f54e0, 0x16)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:530 +0x90
runtime.sysMap(0xc830500000, 0x10000000, 0x499600, 0xc49cb8)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/mem_linux.go:206 +0x9b
runtime.(*mheap).sysAlloc(0xc2ff00, 0x10000000, 0xc820000180)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/malloc.go:429 +0x191
runtime.(*mheap).grow(0xc2ff00, 0x8000, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/mheap.go:651 +0x63
runtime.(*mheap).allocSpanLocked(0xc2ff00, 0x7ffc, 0xc2ae60)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/mheap.go:553 +0x4f6
runtime.(*mheap).alloc_m(0xc2ff00, 0x7ffc, 0xffffff0100000000, 0x7f61fe28ddd0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7f61fe28dde8)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0xc2ff00, 0x7ffc, 0x10100000000, 0x20)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0xfff8000, 0xc800000001, 0xc8201741b0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xc820020000)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:245 fp=0xc820174048 sp=0xc820174040
runtime.mallocgc(0xfff8000, 0x82b420, 0xc800000001, 0xc82002ec00)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/malloc.go:665 +0x9eb fp=0xc820174120 sp=0xc820174048
runtime.newarray(0x82b420, 0xfff8000, 0xc8201741c0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/malloc.go:798 +0xc9 fp=0xc820174160 sp=0xc820174120
runtime.makeslice(0x819fa0, 0xfff8000, 0xfff8000, 0x0, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/slice.go:32 +0x165 fp=0xc8201741b0 sp=0xc820174160
bytes.makeSlice(0xfff8000, 0x0, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/bytes/buffer.go:198 +0x64 fp=0xc820174200 sp=0xc8201741b0
bytes.(*Buffer).grow(0xc8201648c0, 0x8000, 0x8000)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/bytes/buffer.go:106 +0x282 fp=0xc8201742a8 sp=0xc820174200
bytes.(*Buffer).Write(0xc8201648c0, 0xc820128000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/bytes/buffer.go:134 +0x4b fp=0xc820174300 sp=0xc8201742a8
io.(*multiWriter).Write(0xc82038a980, 0xc820128000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/io/multi.go:43 +0xda fp=0xc820174390 sp=0xc820174300
io.copyBuffer(0x7f61ffa079d8, 0xc82038a980, 0x7f61ffa07a28, 0xc82038a9a0, 0xc820128000, 0x8000, 0x8000, 0x7ff8000, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/io/io.go:382 +0x2c9 fp=0xc820174450 sp=0xc820174390
io.Copy(0x7f61ffa079d8, 0xc82038a980, 0x7f61ffa07a28, 0xc82038a9a0, 0xc82038a980, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/io/io.go:350 +0x64 fp=0xc8201744a8 sp=0xc820174450
io.CopyN(0x7f61ffa079d8, 0xc82038a980, 0x7f61ff9fc2d0, 0xc82002c008, 0x20d00000, 0x1c600000070, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/io/io.go:326 +0xf7 fp=0xc820174528 sp=0xc8201744a8
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.hashCopyN(0xc8200bcfe0, 0x14, 0xc82000ba10, 0x28, 0x1, 0x0, 0x995898, 0x2, 0xa7d110, 0x14, ...)
        /home/harsha/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api-put-object-common.go:196 +0x441 fp=0xc820174640 sp=0xc820174528
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.putObjectMultipartStream(0xc8200bcfe0, 0x14, 0xc82000ba10, 0x28, 0x1, 0x0, 0x995898, 0x2, 0xa7d110,
0x14, ...)
        /home/harsha/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api-put-object-multipart.go:117 +0x49c fp=0xc820174d88 sp=0xc820174640
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.putObjectMultipart(0xc8200bcfe0, 0x14, 0xc82000ba10, 0x28, 0x1, 0x0, 0x995898, 0x2, 0xa7d110, 0x14, ...)
        /home/harsha/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api-put-object-multipart.go:62 +0x372 fp=0xc820174ed8 sp=0xc820174d88
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.PutObjectWithProgress(0xc8200bcfe0, 0x14, 0xc82000ba10, 0x28, 0x1, 0x0, 0x995898, 0x2, 0xa7d110, 0x14, ...)
        /home/harsha/mygo/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api-put-object-progress.go:89 +0x863 fp=0xc820175148 sp=0xc820174ed8
main.(*s3Client).Put(0xc8201608e0, 0x7f61ff9fc2d0, 0xc82002c008, 0xffffffffffffffff, 0xc8201bcc20, 0xf, 0x0, 0x0, 0x4a, 0xc82001a910)
        /home/harsha/mygo/src/github.com/minio/mc/client-s3.go:163 +0x12e fp=0xc820175350 sp=0xc820175148
main.putTargetStreamFromAlias(0x7ffdf38c15d9, 0x7, 0xc82001a9b0, 0x4a, 0x7f61ff9fc2d0, 0xc82002c008, 0xffffffffffffffff, 0x0, 0x0, 0xc82016226b, ...)
        /home/harsha/mygo/src/github.com/minio/mc/common-methods.go:82 +0x223 fp=0xc8201753f0 sp=0xc820175350
main.putTargetStream(0x7ffdf38c15d9, 0x39, 0x7f61ff9fc2d0, 0xc82002c008, 0xffffffffffffffff, 0xc820162270, 0x5)
        /home/harsha/mygo/src/github.com/minio/mc/common-methods.go:95 +0x1d1 fp=0xc820175490 sp=0xc8201753f0
main.pipe(0x7ffdf38c15d9, 0x39, 0x827320)
        /home/harsha/mygo/src/github.com/minio/mc/pipe-main.go:75 +0x118 fp=0xc820175528 sp=0xc820175490
main.mainPipe(0xc820106b40)
        /home/harsha/mygo/src/github.com/minio/mc/pipe-main.go:108 +0x212 fp=0xc820175628 sp=0xc820175528
github.com/minio/mc/vendor/github.com/minio/cli.Command.Run(0x996070, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa514a0, 0x58, 0x0, ...)
        /home/harsha/mygo/src/github.com/minio/mc/vendor/github.com/minio/cli/command.go:117 +0x19b2 fp=0xc820175c60 sp=0xc820175628
github.com/minio/mc/vendor/github.com/minio/cli.(*App).Run(0xc8200e8360, 0xc82000a300, 0x3, 0x3, 0x0, 0x0)
        /home/harsha/mygo/src/github.com/minio/mc/vendor/github.com/minio/cli/app.go:186 +0x476 fp=0xc820175e58 sp=0xc820175c60
github.com/minio/mc/vendor/github.com/minio/cli.(*App).RunAndExitOnError(0xc8200e8360)
        /home/harsha/mygo/src/github.com/minio/mc/vendor/github.com/minio/cli/app.go:197 +0x45 fp=0xc820175ea0 sp=0xc820175e58
main.main()
        /home/harsha/mygo/src/github.com/minio/mc/main.go:207 +0x18d fp=0xc820175f40 sp=0xc820175ea0
runtime.main()
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:188 +0x2b0 fp=0xc820175f90 sp=0xc820175f40
runtime.goexit()
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820175f98 sp=0xc820175f90
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/os/signal/signal_unix.go:28 +0x37

goroutine 23 [select]:
net/http.(*persistConn).writeLoop(0xc8200c6270)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/http/transport.go:854 +0x10cb
goroutine 19 [IO wait]:
net.runtime_pollWait(0x7f61ffa01ad0, 0x72, 0xc820254000)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820222220, 0x72, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820222220, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202221c0, 0xc820254000, 0x1000, 0x1000, 0x0, 0x7f61ff9f8050, 0xc820010028)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002c198, 0xc820254000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201c30b0, 0x7f61ffa01e88, 0xc82002c198, 0x5, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820130300, 0xa7b817, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820130300, 0xc820232000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x7f61ff9c42f8, 0xc820130300, 0xc82015b8c8, 0xc820232000, 0x1000, 0x1000, 0x46bdf3, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc8203b1fa0, 0xc820232000, 0x1000, 0x1000, 0xc820055d0d, 0x0, 0x0)
        <autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820016ae0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820016ae0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82015b860)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/http/transport.go:853 +0x10a6

goroutine 20 [select]:
net/http.(*persistConn).writeLoop(0xc82015b860)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/http/transport.go:854 +0x10cb
goroutine 22 [IO wait]:
net.runtime_pollWait(0x7f61ffa01a10, 0x72, 0xc820225800)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820223720, 0x72, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820223720, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202236c0, 0xc820225800, 0x400, 0x400, 0x0, 0x7f61ff9f8050, 0xc820010028)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002c028, 0xc820225800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82035ca80, 0x7f61ffa01e88, 0xc82002c028, 0x5, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820429b00, 0xa7b817, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820429b00, 0xc820151000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x7f61ff9c42f8, 0xc820429b00, 0xc8200c62d8, 0xc820151000, 0x1000, 0x1000, 0x46bdf3, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc820395c60, 0xc820151000, 0x1000, 0x1000, 0xc820113d0d, 0x0, 0x0)
        <autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820017ec0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820017ec0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200c6270)
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
        /home/harsha/.gimme/versions/go1.6.linux.amd64/src/net/http/transport.go:853 +0x10a6
```

**Comment by harshavardhana** [comment]
@yoavlt what is the file size of the movie.mp4?

**Comment by harshavardhana** [comment]
@yoavlt can you try 'mc cp movie.mp4 awsdisk/target/file_path.mp4'? - is there a specific reason to do 'mc pipe' ?

**Comment by yoavlt** [comment]
Sorry, it is 238 MB and machine memory is 2GB.

**Comment by yoavlt** [comment]
I thought `mc pipe` is faster than `mc pipe`. What is difference?

**Comment by yoavlt** [comment]
@harshavardhana It uploaded successfuly when I use `mc cp`.  What is the difference between `mc cp` and `mc pipe` on large file?

**Comment by harshavardhana** [comment]
> I thought mc pipe is faster than mc cp. What is difference?

mc cp is same and better than 'mc pipe' .  'mc cp' provides session and being able to properly resume the download in case of network errors etc. 'mc pipe' is used when prior length of the object cannot be known or for you have a streaming upload like you wish to do a `mysqldump | mc pipe`

**Comment by harshavardhana** [comment]
'mc pipe' would try to allocate '530MB' worth of memory for doing a streaming upload,  but this looks like a simple bug to reproduce. Will see why 'mc pipe' is using a lot of memory. 

Thanks @yoavlt

**Comment by yoavlt** [comment]
OK! Thanks @harshavardhana ! I use `mc cp`. :+1:

**Comment by harshavardhana** [comment]
Reproduced this problem @yoavlt - looks like 'mc pipe' is not behaving that well.

**Comment by mkeedlinger** [comment]
I am still having this issue. I am using it to create a tar backup and upload it.
```
tar cf - folder_to_backup/ | gzip -9 | mc pipe s3/bucket/backup.tar.gz
```
The folder comes out to about 8 GB.

The version I am using is `2017-06-15T03:38:43Z`.

**Comment by harshavardhana** [comment]
> I am still having this issue. I am using it to create a tar backup and upload it.
> 
> tar cf - folder_to_backup/ | gzip -9 | mc pipe s3/bucket/backup.tar.gz
> The folder comes out to about 8 GB.
> 
> The version I am using is 2017-06-15T03:38:43Z.

There is a bug on this we are fixing on https://github.com/minio/minio-go/pull/733
