### ISSUE TITLE
Rare crash: concurrent map access

### ISSUE THREAD

**Issue by vadmeste** [minio/mc#1861]
This occured in a copy loop (mc cp) of a 128 mb file to a remote bucket

```
fatal error: concurrent map writes

goroutine 53 [running]:
runtime.throw(0x877a01, 0x15)
        /home/vadmeste/work/go/src/runtime/panic.go:566 +0x95 fp=0xc4203d17d8 sp=0xc4203d17b8
runtime.mapassign1(0x8023c0, 0xc420400210, 0xc4203d1a58, 0xc4203d1c60)
        /home/vadmeste/work/go/src/runtime/hashmap.go:458 +0x8ef fp=0xc4203d18c0 sp=0xc4203d17d8
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.putObjectMultipartFromFile.func1(0xc420414000, 0xc4203c3860, 0x4000000, 0x2, 0x4000000, 0xc4203c6108, 0x8000000, 0xa4cc40, 0xc4204502f0, 0xc4201db0f0, ...)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api-put-object-file.go:255 +0x81d fp=0xc4203d1f08 sp=0xc4203d18c0
runtime.goexit()
        /home/vadmeste/work/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4203d1f10 sp=0xc4203d1f08
created by github.com/minio/mc/vendor/github.com/minio/minio-go.Client.putObjectMultipartFromFile
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api-put-object-file.go:264 +0x518

goroutine 1 [runnable]:
io.(*LimitedReader).Read(0xc420235c40, 0xc420316000, 0x2000, 0x2000, 0x2000, 0x0, 0x0)
        /home/vadmeste/work/go/src/io/io.go:429
io/ioutil.devNull.ReadFrom(0x0, 0xa4c240, 0xc420235c40, 0x80d140, 0x8b1801, 0x7fcae9831bd0)
        /home/vadmeste/work/go/src/io/ioutil/ioutil.go:151 +0x85
io/ioutil.(*devNull).ReadFrom(0xc420010360, 0xa4c240, 0xc420235c40, 0xc4203d48c8, 0x1, 0x18)
        <autogenerated>:9 +0x66
io.copyBuffer(0xa4dbc0, 0xc420010360, 0xa4c240, 0xc420235c40, 0x0, 0x0, 0x0, 0x81e0a0, 0xc420000101, 0xc420235c40)
        /home/vadmeste/work/go/src/io/io.go:384 +0x323
io.Copy(0xa4dbc0, 0xc420010360, 0xa4c240, 0xc420235c40, 0xc4204541e0, 0xc4203d4be8, 0xc4203d4901)
        /home/vadmeste/work/go/src/io/io.go:360 +0x68
io.CopyN(0xa4dbc0, 0xc420010360, 0xa4c0c0, 0xc4203caf00, 0x4000000, 0x2, 0x4000000, 0xc4203c6108)
        /home/vadmeste/work/go/src/io/io.go:336 +0x8c
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.putObjectMultipartFromFile(0xc420311c60, 0x5, 0xc420311c68, 0x8, 0x2, 0x0, 0x86fae4, 0x2, 0x8b51f0, 0x14, ...)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api-put-object-file.go:282 +0x89e
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.putObjectMultipart(0xc420311c60, 0x5, 0xc420311c68, 0x8, 0x2, 0x0, 0x86fae4, 0x2, 0x8b51f0, 0x14, ...)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api-put-object-multipart.go:52 +0x15e
github.com/minio/mc/vendor/github.com/minio/minio-go.Client.PutObjectWithProgress(0xc420311c60, 0x5, 0xc420311c68, 0x8, 0x2, 0x0, 0x86fae4, 0x2, 0x8b51f0, 0x14, ...)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/minio/minio-go/api-put-object-progress.go:92 +0x80e
github.com/minio/mc/cmd.(*s3Client).Put(0xc4203ad920, 0xa4cc00, 0xc4204502f0, 0x8000000, 0xc420413530, 0x18, 0xa4c0c0, 0xc4203caf00, 0x47480e, 0x0)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/client-s3.go:528 +0x169
github.com/minio/mc/cmd.putTargetStreamFromAlias(0xc420469990, 0xc, 0xc420411980, 0x2b, 0xa4cc00, 0xc4204502f0, 0x8000000, 0xa4c0c0, 0xc4203caf00, 0x2f, ...)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/common-methods.go:85 +0x205
github.com/minio/mc/cmd.doCopy(0x0, 0x0, 0xc420324b00, 0xc420469990, 0xc, 0xc420324b80, 0x0, 0xc420411800, 0xc4201e6d20, 0x0, ...)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/cp-main.go:205 +0xe4a
github.com/minio/mc/cmd.doCopySession(0xc4204105d0)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/cp-main.go:377 +0x4e5
github.com/minio/mc/cmd.mainCopy(0xc4201221e0)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/cp-main.go:427 +0x1ae
github.com/minio/mc/vendor/github.com/minio/cli.Command.Run(0x86faac, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8786d7, 0x17, 0x0, ...)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/minio/cli/command.go:117 +0xbc1
github.com/minio/mc/vendor/github.com/minio/cli.(*App).Run(0xc4201465a0, 0xc42000c3c0, 0x4, 0x4, 0x0, 0x0)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/minio/cli/app.go:186 +0x246
github.com/minio/mc/vendor/github.com/minio/cli.(*App).RunAndExitOnError(0xc4201465a0)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/minio/cli/app.go:197 +0x4f
github.com/minio/mc/cmd.Main()
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/main.go:95 +0x163
main.main()
        /home/vadmeste/work/gospace/src/github.com/minio/mc/main.go:22 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/vadmeste/work/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [chan receive]:
github.com/minio/mc/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc42006a1e0, 0xc42006a120)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0x5a
created by github.com/minio/mc/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0x181

goroutine 6 [chan receive]:
github.com/minio/mc/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc42006a1e0, 0xc42006a180)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x94
created by github.com/minio/mc/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x1ad

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
        /home/vadmeste/work/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /home/vadmeste/work/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /home/vadmeste/work/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 21 [select]:
github.com/minio/mc/vendor/github.com/cheggaaa/pb.(*ProgressBar).refresher(0xc4203caf00)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/cheggaaa/pb/pb.go:427 +0x109
created by github.com/minio/mc/vendor/github.com/cheggaaa/pb.(*ProgressBar).Start
        /home/vadmeste/work/gospace/src/github.com/minio/mc/vendor/github.com/cheggaaa/pb/pb.go:123 +0xb7

goroutine 18 [IO wait]:
net.runtime_pollWait(0x7fcae9887cc0, 0x72, 0x5)
        /home/vadmeste/work/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420149720, 0x72, 0xc42003d9d0, 0xc420010180)
        /home/vadmeste/work/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420149720, 0xa4e400, 0xc420010180)
        /home/vadmeste/work/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4201496c0, 0xc42015c000, 0x1000, 0x1000, 0x0, 0xa4e400, 0xc420010180)
        /home/vadmeste/work/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42002e000, 0xc42015c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/vadmeste/work/go/src/net/net.go:173 +0x70
net/http.(*persistConn).Read(0xc42000b200, 0xc42015c000, 0x1000, 0x1000, 0x30, 0xc42003db58, 0x43b5ac)
        /home/vadmeste/work/go/src/net/http/transport.go:1261 +0x154
bufio.(*Reader).fill(0xc42006a0c0)
        /home/vadmeste/work/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc42006a0c0, 0x1, 0x0, 0x1, 0xc420454c00, 0xc420454c60, 0x0)
        /home/vadmeste/work/go/src/bufio/bufio.go:129 +0x62
net/http.(*persistConn).readLoop(0xc42000b200)
        /home/vadmeste/work/go/src/net/http/transport.go:1418 +0x1a1
created by net/http.(*Transport).dialConn
        /home/vadmeste/work/go/src/net/http/transport.go:1062 +0x4e9

goroutine 19 [select]:
net/http.(*persistConn).writeLoop(0xc42000b200)
        /home/vadmeste/work/go/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
        /home/vadmeste/work/go/src/net/http/transport.go:1063 +0x50e

goroutine 16 [chan receive]:
github.com/minio/mc/cmd.signalTrap.func1(0xc4203ac660, 0x2, 0x2, 0xc420154850, 0xc420154850)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/signals.go:39 +0xb8
created by github.com/minio/mc/cmd.signalTrap
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/signals.go:46 +0x84

goroutine 50 [chan send]:
github.com/minio/mc/cmd.cursorAnimate.func1(0x873ae0, 0xc, 0xc4201e63c0)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/progress-bar.go:131 +0x77
created by github.com/minio/mc/cmd.cursorAnimate
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/progress-bar.go:134 +0x72

goroutine 20 [select]:
github.com/minio/mc/cmd.(*accounter).writer(0xc4201e6d20)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/accounting-reader.go:67 +0x11a
created by github.com/minio/mc/cmd.newAccounter
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/accounting-reader.go:48 +0x11f

goroutine 35 [select, locked to thread]:
runtime.gopark(0x8b41e8, 0x0, 0x87109b, 0x6, 0x18, 0x2)
        /home/vadmeste/work/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc4201d1f30, 0x0, 0x18)
        /home/vadmeste/work/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc4201d1f30)
        /home/vadmeste/work/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /home/vadmeste/work/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
        /home/vadmeste/work/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 22 [select]:
github.com/minio/mc/cmd.doCopySession.func1(0xc420469950, 0xc420154850, 0xc4204105d0, 0xc4201e6f00)
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/cp-main.go:325 +0x7f9
created by github.com/minio/mc/cmd.doCopySession
        /home/vadmeste/work/gospace/src/github.com/minio/mc/cmd/cp-main.go:365 +0x2b8

goroutine 40 [IO wait]:
net.runtime_pollWait(0x7fcae9887c00, 0x72, 0x9)
        /home/vadmeste/work/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420180370, 0x72, 0xc4204619d0, 0xc420010180)
        /home/vadmeste/work/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420180370, 0xa4e400, 0xc420010180)
        /home/vadmeste/work/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420180310, 0xc420407000, 0x1000, 0x1000, 0x0, 0xa4e400, 0xc420010180)
        /home/vadmeste/work/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42002e240, 0xc420407000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/vadmeste/work/go/src/net/net.go:173 +0x70
net/http.(*persistConn).Read(0xc420312b00, 0xc420407000, 0x1000, 0x1000, 0x30, 0xc420461b58, 0x43b5ac)
        /home/vadmeste/work/go/src/net/http/transport.go:1261 +0x154
bufio.(*Reader).fill(0xc4204dd320)
        /home/vadmeste/work/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc4204dd320, 0x1, 0x0, 0x1, 0xc4204dd380, 0xc4204dd3e0, 0x0)
        /home/vadmeste/work/go/src/bufio/bufio.go:129 +0x62
net/http.(*persistConn).readLoop(0xc420312b00)
        /home/vadmeste/work/go/src/net/http/transport.go:1418 +0x1a1
created by net/http.(*Transport).dialConn
        /home/vadmeste/work/go/src/net/http/transport.go:1062 +0x4e9

goroutine 41 [select]:
net/http.(*persistConn).writeLoop(0xc420312b00)
        /home/vadmeste/work/go/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
        /home/vadmeste/work/go/src/net/http/transport.go:1063 +0x50e

```

**Comment by harshavardhana** [comment]
Looks like minio-go bug. Closing it here. Can you reopen on minio-go ?
