### ISSUE TITLE
mc can't add TLS host

### ISSUE THREAD

**Issue by marvinholze** [minio/mc#2608]
## Expected behavior
connect to minio server with TLS

## Actual behavior
```
root@minio01[~]$ ./mc config host add minio1 https://192.168.127.117:9443 ACCESS_KEY SECRET_KEY
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x63a17b]

goroutine 1 [running]:
crypto/x509.(*CertPool).AddCert(0x0, 0xc4200c9700)
        /opt/go/src/crypto/x509/cert_pool.go:95 +0x6b
crypto/x509.(*CertPool).AppendCertsFromPEM(0x0, 0xc4202b2000, 0x4cd, 0x6cd, 0x6cd)
        /opt/go/src/crypto/x509/cert_pool.go:128 +0x13d
github.com/minio/mc/cmd.loadRootCAs()
        /q/.q/sources/gopath/src/github.com/minio/mc/cmd/certs.go:133 +0x88
github.com/minio/mc/cmd.initMC()
        /q/.q/sources/gopath/src/github.com/minio/mc/cmd/main.go:210 +0x73
github.com/minio/mc/cmd.registerBefore(0xc4200c2b00, 0xc4200c2b00, 0xc)
        /q/.q/sources/gopath/src/github.com/minio/mc/cmd/main.go:227 +0x83
github.com/minio/mc/vendor/github.com/minio/cli.(*App).Run(0xc4200b11e0, 0xc42009e000, 0x9, 0x9, 0x0, 0x0)
        /q/.q/sources/gopath/src/github.com/minio/mc/vendor/github.com/minio/cli/app.go:245 +0x750
github.com/minio/mc/vendor/github.com/minio/cli.(*App).RunAndExitOnError(0xc4200b11e0)
        /q/.q/sources/gopath/src/github.com/minio/mc/vendor/github.com/minio/cli/app.go:281 +0x53
github.com/minio/mc/cmd.Main()
        /q/.q/sources/gopath/src/github.com/minio/mc/cmd/main.go:96 +0x1e6
main.main()
        /q/.q/sources/gopath/src/github.com/minio/mc/main.go:28 +0x20
```

## Steps to reproduce the behavior
Setup a distributed Minio Server with TLS
connect with `mc config host add minio1 https://192.168.127.117:9443 ACCESS_KEY SECRET_KEY` 

## mc version
- (paste output of `mc version`)

```
Version: 2018-11-06T01:12:20Z
Release-tag: RELEASE.2018-11-06T01-12-20Z
Commit-id: b827fac6356f80354a1cf61f43cf5e5b60bbb511
```

**Comment by sinhaashish** [comment]
@marvinholze  where is the CA certificates kept in your setup?

**Comment by eco-minio** [comment]
@marvinholze I tested this with latest minio server and mc, it works as expected.  If you have a self signed certificate you will need to add `--insecure`:
```
mc config host add myminio https://localhost:9000 minio minio123 --insecure
Added `myminio` successfully.
```
Also, make sure that your cert and key are named public.crt and private.key, and are located in ~/.minio/certs.

**Comment by kannappanr** [comment]
@marvinholze Closing this as stale and working as intended. Please feel free to reopen the issue if you feel otherwise.
