### ISSUE TITLE
mc admin console results in runtime error

### ISSUE THREAD

**Issue by philipkozeny** [minio/mc#2911]
## Expected behavior

I am running `mc admin console storage` which always results in

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xabc9f2]

goroutine 1 [running]:
github.com/minio/mc/cmd.logMessage.String(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/q/.q/sources/gopath/src/github.com/minio/mc/cmd/admin-console.go:96 +0x42
github.com/minio/mc/cmd.printMsg(0xe5f580, 0xc0002e2210)
	/q/.q/sources/gopath/src/github.com/minio/mc/cmd/print.go:30 +0xeb
github.com/minio/mc/cmd.mainAdminConsole(0xc00008dc80, 0x0, 0x0)
	/q/.q/sources/gopath/src/github.com/minio/mc/cmd/admin-console.go:179 +0x448
github.com/minio/cli.HandleAction(0xc09ae0, 0xd78fc0, 0xc00008dc80, 0xc0000b9a00, 0x0)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/app.go:498 +0xc8
github.com/minio/cli.Command.Run(0xd288a7, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd44e53, 0x22, 0x0, ...)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/command.go:221 +0x991
github.com/minio/cli.(*App).RunAsSubcommand(0xc000269380, 0xc00008d080, 0x0, 0x0)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/app.go:387 +0x7fa
github.com/minio/cli.Command.startApp(0xd264ba, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd349bc, 0x14, 0x0, ...)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/command.go:309 +0x809
github.com/minio/cli.Command.Run(0xd264ba, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd349bc, 0x14, 0x0, ...)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/command.go:107 +0x127b
github.com/minio/cli.(*App).Run(0xc0002681a0, 0xc0000ba040, 0x4, 0x4, 0x0, 0x0)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/app.go:261 +0x6ab
github.com/minio/mc/cmd.Main(0xc0000ba040, 0x4, 0x4)
	/q/.q/sources/gopath/src/github.com/minio/mc/cmd/main.go:110 +0x29c
main.main()
	/q/.q/sources/gopath/src/github.com/minio/mc/main.go:34 +0x45
```

I have tried different minio instances, doesn't matter.

## mc version
Version: 2019-09-24T01:36:20Z
Release-tag: RELEASE.2019-09-24T01-36-20Z
Commit-id: 643835013047aa27ed35de0ac5a4ab9538f0cd68

## System information
Linux tools-1 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

Connecting to a remote hosts

**Comment by vadmeste** [comment]
@philipkozeny thanks for reporting, it will get fixed quickly soon

**Comment by vadmeste** [comment]
> @philipkozeny thanks for reporting, it will get fixed quickly soon

I was able to reproduce this issue @philipkozeny but it is already fixed, you should not see this in the next release of minio & mc

**Comment by kannappanr** [comment]
@philipkozeny Your `MinIO` is probably one of `RELEASE.2019-09-26T19-42-35Z` or `RELEASE.2019-09-25T18-25-51Z` .  The fix for this issue has been merged in master. You should get it in the next release of `mc`. I don't think you would require a newer version of `MinIO` .

**Comment by kannappanr** [comment]
@philipkozeny Closing this issue as this has already been fixed in the master. `mc` should be released early next week.
