### ISSUE TITLE
'mc cp' with no arguments panics when printing help

### ISSUE THREAD

**Issue by maelvls** [minio/mc#3046]
The `mc cp` with no argument panics because of some issues with printing help. `mc cp --help` also panics.

```
% mc cp
panic: template: help:62: unexpected "}" in operand

goroutine 1 [running]:
text/template.Must(...)
	text/template/helper.go:23
github.com/minio/cli.printHelpCustom(0x4a86ec0, 0xc0000ce008, 0x4994162, 0xe42, 0x49426a0, 0xc0002a0600, 0x0)
	github.com/minio/cli@v1.22.0/help.go:260 +0x514
github.com/minio/cli.ShowCommandHelp(0xc0002376c0, 0x494c37d, 0x2, 0xc0001a5568, 0x400e546)
	github.com/minio/cli@v1.22.0/help.go:203 +0x4ae
github.com/minio/cli.ShowCommandHelpAndExit(0xc0002376c0, 0x494c37d, 0x2, 0x1)
	github.com/minio/cli@v1.22.0/help.go:167 +0x3f
github.com/minio/mc/cmd.checkCopySyntax(0xc0002376c0, 0xc000283b00)
	github.com/minio/mc@/cmd/cp-url-syntax.go:29 +0x74e
github.com/minio/mc/cmd.mainCopy(0xc0002376c0, 0x0, 0x2376c0)
	github.com/minio/mc@/cmd/cp-main.go:558 +0xd6
github.com/minio/cli.HandleAction(0x482c1c0, 0x49a2e80, 0xc0002376c0, 0xc0002a2000, 0x0)
	github.com/minio/cli@v1.22.0/app.go:498 +0xc8
github.com/minio/cli.Command.Run(0x494c37d, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x495511c, 0xc, 0x0, ...)
	github.com/minio/cli@v1.22.0/command.go:225 +0x991
github.com/minio/cli.(*App).Run(0xc0002361a0, 0xc0000de020, 0x2, 0x2, 0x0, 0x0)
	github.com/minio/cli@v1.22.0/app.go:261 +0x6ab
github.com/minio/mc/cmd.Main(0xc0000de020, 0x2, 0x2)
	github.com/minio/mc@/cmd/main.go:113 +0x29c
main.main()
	github.com/minio/mc@/main.go:34 +0x45
```

```
% mc --version
mc version RELEASE.2020-01-13T22-49-03Z
```

macOS Catalina (10.15.1 -- 19B88)

**Comment by harshavardhana** [comment]
Looks like a help template issue, perhaps some typo.

**Comment by maelvls** [comment]
Templated string is
```
"NAME:
  {{.HelpName}} - {{.Usage}}

USAGE:
  {{.HelpName}} [FLAGS] SOURCE [SOURCE...] TARGET

FLAGS:
  {{range .VisibleFlags}}{{.}}
  {{end}}
ENVIRONMENT VARIABLES:
  MC_ENCRYPT:      list of comma delimited prefixes
  MC_ENCRYPT_KEY:  list of comma delimited prefix=secret values

EXAMPLES:
  01. Copy a list of objects from local file system to Amazon S3 cloud storage.
      {{.Prompt}} {{.HelpName}} Music/*.ogg s3/jukebox/

  02. Copy a folder recursively from MinIO cloud storage to Amazon S3 cloud storage.
      {{.Prompt}} {{.HelpName}} --recursive play/mybucket/burningman2011/ s3/mybucket/

  03. Copy multiple local folders recursively to MinIO cloud storage.
      {{.Prompt}} {{.HelpName}} --recursive backup/2014/ backup/2015/ play/archive/

  04. Copy a bucket recursively from aliased Amazon S3 cloud storage to local filesystem on Windows.
      {{.Prompt}} {{.HelpName}} --recursive s3\documents\2014\ C:\Backups\2014

  05. Copy files older than 7 days and 10 hours from MinIO cloud storage to Amazon S3 cloud storage.
      {{.Prompt}} {{.HelpName}} --older-than 7d10h play/mybucket/burningman2011/ s3/mybucket/

  06. Copy files newer than 7 days and 10 hours from MinIO cloud storage to a local path.
      {{.Prompt}} {{.HelpName}} --newer-than 7d10h play/mybucket/burningman2011/ ~/latest/

  07. Copy an object with name containing unicode characters to Amazon S3 cloud storage.
      {{.Prompt}} {{.HelpName}} 本語 s3/andoria/

  08. Copy a local folder with space separated characters to Amazon S3 cloud storage.
      {{.Prompt}} {{.HelpName}} --recursive 'workdir/documents/May 2014/' s3/miniocloud

  09. Copy a folder with encrypted objects recursively from Amazon S3 to MinIO cloud storage.
      {{.Prompt}} {{.HelpName}} --recursive --encrypt-key "s3/documents/=32byteslongsecretkeymustbegiven1,myminio/documents/=32byteslongsecretkeymustbegiven2" s3/documents/ myminio/documents/

  10. Copy a folder with encrypted objects recursively from Amazon S3 to MinIO cloud storage. In case the encryption key contains non-printable character like tab, pass the
      base64 encoded string as key.
      {{.Prompt}} {{.HelpName}} --recursive --encrypt-key "s3/documents/=MzJieXRlc2xvbmdzZWNyZWFiY2RlZmcJZ2l2ZW5uMjE=,myminio/documents/=MzJieXRlc2xvbmdzZWNyZWFiY2RlZmcJZ2l2ZW5uMjE=" s3/documents/ myminio/documents/

  11. Copy a list of objects from local file system to MinIO cloud storage with specified metadata, separated by ";"
      {{.Prompt}} {{.HelpName}} --attr "key1=value1;key2=value2" Music/*.mp4 play/mybucket/

  12. Copy a folder recursively from MinIO cloud storage to Amazon S3 cloud storage with Cache-Control and custom metadata, separated by ";".
      {{.Prompt}} {{.HelpName}} --attr "Cache-Control=max-age=90000,min-fresh=9000;key1=value1;key2=value2" --recursive play/mybucket/burningman2011/ s3/mybucket/

  13. Copy a text file to an object storage and assign REDUCED_REDUNDANCY storage-class to the uploaded object.
      {{.Prompt}} {{.HelpName}} --storage-class REDUCED_REDUNDANCY myobject.txt play/mybucket

  14. Copy a text file to an object storage and create or resume copy session.
      {{.Prompt}} {{.HelpName}} --recursive --continue dir/ play/mybucket

  15. Copy a text file to an object storage and preserve the file system attribute as metadata.
      {{.Prompt}} {{.HelpName}} -a myobject.txt play/mybucket

  16. Copy a text file to an object storage with object lock mode set to 'GOVERNANCE' with retention date.
      {{.Prompt}} {{.HelpName} --attr "x-amz-object-lock-mode=GOVERNANCE;x-amz-object-lock-retain-until-date=2020-01-11T01:57:02Z" locked.txt play/locked-bucket/
```

The last line has a missing `}` apparently:
```
      {{.Prompt}} {{.HelpName} --attr "x-amz-object-lock-mode=GOVERNANCE;x-amz-object-lock-retain-until-date=2020-01-11T01:57:02Z" locked.txt play/locked-bucket/
```
