### ISSUE TITLE
mc cp -h returning `unexpected "}" in operand` error

### ISSUE THREAD

**Issue by kaankabalak** [minio/mc#3055]
## Expected behavior
`mc cp -h` command should be returning the help prompt instead of an error.

## Actual behavior
`mc cp -h` command returns the following error:
```
panic: template: help:62: unexpected "}" in operand

goroutine 1 [running]:
text/template.Must(...)
	/opt/go/src/text/template/helper.go:23
github.com/minio/cli.printHelpCustom(0x1a7d240, 0xc00000e018, 0x198a6f5, 0xe42, 0x1938a80, 0xc000199500, 0x0)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/help.go:260 +0x514
github.com/minio/cli.ShowCommandHelp(0xc000285520, 0x1942769, 0x2, 0x1, 0xc000285520)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/help.go:203 +0x4ae
github.com/minio/cli.checkCommandHelp(0xc000285520, 0x1942769, 0x2, 0xc000215440)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/help.go:303 +0x7d
github.com/minio/cli.Command.Run(0x1942769, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x194b55e, 0xc, 0x0, ...)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/command.go:192 +0x930
github.com/minio/cli.(*App).Run(0xc000284000, 0xc0000300c0, 0x3, 0x3, 0x0, 0x0)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/app.go:261 +0x6ab
github.com/minio/mc/cmd.Main(0xc0000300c0, 0x3, 0x3)
	/q/.q/sources/gopath/src/github.com/minio/mc/cmd/main.go:113 +0x29c
main.main()
	/q/.q/sources/gopath/src/github.com/minio/mc/main.go:34 +0x45
```

## Steps to reproduce the behavior
Type the `mc cp -h` command.

## mc --version
- RELEASE.2020-01-13T22-49-03Z

## System information
macOS Catalina Version 10.15.1

**Comment by kaankabalak** [comment]
Fixed with #3047
