### ISSUE TITLE
'admin console' segmentation violation with https

### ISSUE THREAD

**Issue by antitbone** [minio/mc#3078]
mc version RELEASE.2020-02-05T20-07-22Z
minio version RELEASE.2020-02-07T23-28-16Z
Centos 7.7

```bash
minio server --certs-dir /etc/minio/certs https://node{1...5}.xxx:9000/minio/disk{2...5}
```

Identical wildcard certificate on all nodes.

The cluster initializes, starts and works correctly.

But, "mc admin console nodeX" generate a segfault.

.mc/config.json
```json
		"node5": {
			"url": "https://node5.xxx:9000",
			"accesskey": "plopplop",
			"secretkey": "plopplop",
			"api": "s3v4",
			"lookup": "auto"
		}
```

```
node5.xxx  Status:         20 Online, 0 Offline.                             
node5.xxx  Endpoint:  https://x.x.73.215:9000  https://x.x.74.81:9000  https://127.0.0.1:9000
node5.xxx
node5.xxx  Browser Access:
node5.xxx     https://x.x.73.215:9000  https://x.x.74.81:9000  https://127.0.0.1:9000
node5.xxx
node5.xxx  Object API (Amazon S3 compatible):
node5.xxx     Go:         https://docs.min.io/docs/golang-client-quickstart-guide
node5.xxx     Java:       https://docs.min.io/docs/java-client-quickstart-guide
node5.xxx     Python:     https://docs.min.io/docs/python-client-quickstart-guide
node5.xxx     JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
node5.xxx     .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xab5601]

goroutine 1 [running]:
github.com/minio/mc/cmd.logMessage.String(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /q/.q/sources/gopath/src/github.com/minio/mc/cmd/admin-console.go:144 +0x121
github.com/minio/mc/cmd.printMsg(0xe62c80, 0xc0002b5a00)
        /q/.q/sources/gopath/src/github.com/minio/mc/cmd/print.go:33 +0xeb
github.com/minio/mc/cmd.mainAdminConsole(0xc0002d4680, 0x0, 0x0)
        /q/.q/sources/gopath/src/github.com/minio/mc/cmd/admin-console.go:206 +0x725
github.com/minio/cli.HandleAction(0xc071e0, 0xd785b0, 0xc0002d4680, 0xc0002b8700, 0x0)
        /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/app.go:498 +0xc8
github.com/minio/cli.Command.Run(0xd25934, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd427cb, 0x22, 0x0, ...)
        /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/command.go:225 +0x991
github.com/minio/cli.(*App).RunAsSubcommand(0xc0002d4000, 0xc000190ea0, 0x0, 0x0)
        /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/app.go:387 +0x7fa
github.com/minio/cli.Command.startApp(0xd23516, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd31dd6, 0x14, 0x0, ...)
        /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/command.go:313 +0x809
github.com/minio/cli.Command.Run(0xd23516, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd31dd6, 0x14, 0x0, ...)
        /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/command.go:111 +0x127b
github.com/minio/cli.(*App).Run(0xc000190b60, 0xc000030050, 0x5, 0x5, 0x0, 0x0)
        /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/app.go:261 +0x6ab
github.com/minio/mc/cmd.Main(0xc000030050, 0x5, 0x5)
        /q/.q/sources/gopath/src/github.com/minio/mc/cmd/main.go:113 +0x29c
main.main()
        /q/.q/sources/gopath/src/github.com/minio/mc/main.go:34 +0x45
```

The other admin commands seem to be functional

Successively tested with 2 wildcard certificats for *.xxx domaine. (Let's Encrypt and DigiCert)

**Comment by kannappanr** [comment]
@antitbone Thanks for reporting. We will take a look
