### ISSUE TITLE
mc cp should show help when no options provided

### ISSUE THREAD

**Issue by designermonkey** [minio/mc#3087]
## Expected behavior

I expected that as with some other bash commands, if I omitted the options, I would be told what the options should be.

## Actual behavior

```
$ mc cp
panic: template: help:62: unexpected "}" in operand

goroutine 1 [running]:
text/template.Must(...)
	/opt/go/src/text/template/helper.go:23
github.com/minio/cli.printHelpCustom(0xe79b20, 0xc000094008, 0xd885fa, 0xe42, 0xd36640, 0xc000288600, 0x0)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/help.go:260 +0x514
github.com/minio/cli.ShowCommandHelp(0xc000261380, 0xd4031d, 0x2, 0xc000159568, 0x40c1b6)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/help.go:203 +0x4ae
github.com/minio/cli.ShowCommandHelpAndExit(0xc000261380, 0xd4031d, 0x2, 0x1)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/help.go:167 +0x3f
github.com/minio/mc/cmd.checkCopySyntax(0xc000261380, 0xc0002842d0)
	/q/.q/sources/gopath/src/github.com/minio/mc/cmd/cp-url-syntax.go:29 +0x74e
github.com/minio/mc/cmd.mainCopy(0xc000261380, 0x0, 0x261380)
	/q/.q/sources/gopath/src/github.com/minio/mc/cmd/cp-main.go:558 +0xd6
github.com/minio/cli.HandleAction(0xc214a0, 0xd97320, 0xc000261380, 0xc000270600, 0x0)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/app.go:498 +0xc8
github.com/minio/cli.Command.Run(0xd4031d, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd49381, 0xc, 0x0, ...)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/command.go:225 +0x991
github.com/minio/cli.(*App).Run(0xc00009dd40, 0xc00009a000, 0x2, 0x2, 0x0, 0x0)
	/q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.22.0/app.go:261 +0x6ab
github.com/minio/mc/cmd.Main(0xc00009a000, 0x2, 0x2)
	/q/.q/sources/gopath/src/github.com/minio/mc/cmd/main.go:113 +0x29c
main.main()
	/q/.q/sources/gopath/src/github.com/minio/mc/main.go:34 +0x45
```

## Steps to reproduce the behavior

```
$ mc cp
```

## mc --version
- RELEASE.2020-01-13T22-49-03Z

## System information

Ubuntu 18.04

**Comment by harshavardhana** [comment]
Please upgrade your mc this issue is already fixed @designermonkey 

```mc update```

**Comment by designermonkey** [comment]
Thanks.
