### ISSUE TITLE
Conflicting config.json and notification.xml files may cause server to crash

### ISSUE THREAD

**Issue by ebozduman** [minio/mc#3155]
## Expected behavior
No crash/panic
## Actual behavior
Crash happens. Here is the stack trace from the server console:
```
2020/04/12 23:42:22 http: panic serving 192.168.1.26:47856: runtime error: slice bounds out of range [3:2]
goroutine 571 [running]:
net/http.(*conn).serve.func1(0xc000707180)
	net/http/server.go:1767 +0x139
panic(0x1b3d1e0, 0xc0000411a0)
	runtime/panic.go:679 +0x1b2
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0xc0007d8a00, 0x204a5c0, 0xc0003a2a80)
	github.com/minio/minio@/cmd/generic-handlers.go:776 +0x272
panic(0x1b3d1e0, 0xc0000411a0)
	runtime/panic.go:679 +0x1b2
github.com/minio/minio/cmd.objectAPIHandlers.GetBucketNotificationHandler(0x1d08be0, 0x1d08bd0, 0xc00044c970, 0xc00044c980, 0x2047f40, 0xc00083e780, 0xc0007d8c00)
	github.com/minio/minio@/cmd/bucket-notification-handlers.go:121 +0x1648
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2007
github.com/minio/minio/cmd.httpTraceAll.func1(0x2047f40, 0xc00083e780, 0xc0007d8c00)
	github.com/minio/minio@/cmd/handler-utils.go:342 +0x148
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2007
github.com/minio/minio/cmd.collectAPIStats.func1(0x2048200, 0xc000707400, 0xc0007d8c00)
	github.com/minio/minio@/cmd/handler-utils.go:402 +0x125
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2007
github.com/minio/minio/cmd.maxClients.func1(0x2048200, 0xc000707400, 0xc0007d8c00)
	github.com/minio/minio@/cmd/handler-utils.go:366 +0x497
net/http.HandlerFunc.ServeHTTP(0xc000366060, 0x2048200, 0xc000707400, 0xc0007d8c00)
	net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00067e0c0, 0x2048200, 0xc000707400, 0xc0007d8a00)
	github.com/gorilla/mux@v1.7.0/mux.go:212 +0xe2
github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP(0x2017160, 0xc00067e0c0, 0x2047f80, 0xc00001d100, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:747 +0x162
github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x201aa20, 0xc000496de0, 0x2047f80, 0xc00001d100, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:762 +0x1d6
github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc000367a40, 0x201ab80, 0xc000496df0, 0x2047f80, 0xc00001d100, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:623 +0xcc
github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP(0x201a980, 0xc0004d3780, 0x2047f80, 0xc00001d100, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:607 +0x5f9
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x201ab20, 0xc000496e20, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:543 +0x106
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x201aa40, 0xc000496e80, 0x50004000000, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:67 +0xcf
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x201ab00, 0xc0004d37a0, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:92 +0x293
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x201aae0, 0xc000496e90, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/crossdomain-xml-handler.go:51 +0x81
github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x201aa00, 0xc000496ea0, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:246 +0x68
github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x201aac0, 0xc000496eb0, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:314 +0xac
github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x201aa80, 0xc000496ec0, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:273 +0x1c2
github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x201a9a0, 0xc000496ed0, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:384 +0x590
github.com/rs/cors.(*Cors).Handler.func1(0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/rs/cors@v1.6.0/cors.go:207 +0x1af
net/http.HandlerFunc.ServeHTTP(0xc0004d3820, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	net/http/server.go:2007 +0x44
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x201b780, 0xc0004d3820, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:524 +0xa8
github.com/minio/minio/cmd.authHandler.ServeHTTP(0x201ab60, 0xc000496f30, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/auth-handler.go:453 +0x3cd
github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP(0x201a960, 0xc000496f40, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:797 +0x481
github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x201aba0, 0xc000496f50, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:135 +0x293
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x201ab40, 0xc000496f60, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/generic-handlers.go:779 +0xac
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	github.com/minio/minio@/cmd/http/server.go:104 +0x2ab
net/http.HandlerFunc.ServeHTTP(0xc000494080, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc0002087e0, 0x204a5c0, 0xc0003a2a80, 0xc0007d8a00)
	net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000707180, 0x2052680, 0xc00083e640)
	net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	net/http/server.go:2928 +0x384
```
## Steps to reproduce the behavior
$ **mc admin config set myminio notify_mysql:myinstance table="minio_table" username="minio" password="Minio123\$" host="localhost" port="3306" database="miniodb"**_Setting new key has been successful.
Please restart your server with `mc admin service restart myminio`.

$ 
$ **mc admin service restart myminio**
Restart command successfully sent to `myminio`.
Restarted `myminio` successfully.
$
$ **mc admin config get myminio notify_mysql**
notify_mysql enable=off format=namespace host= port= username= password= database= dsn_string= table= queue_dir= queue_limit=0 
notify_mysql:myinstance format=namespace host=localhost port=3306 username=minio password=Minio123$ database=miniodb dsn_string= table=minio_table queue_dir= queue_limit=0
$
$ **mc event add myminio/table arn:minio:sqs:us-east-1:myinstance:mysql -p -suffix .txt**
Successfully added arn:minio:sqs:us-east-1:myinstance:mysql
$
$ **mc event add myminio/table arn:minio:sqs:us-east-1:myinstance:mysql -p --event put -suffix .txt**
Successfully added arn:minio:sqs:us-east-1:myinstance:mysql
$
$ **mc event list myminio/table**
arn:minio:sqs:us-east-1:myinstance:mysql   s3:ObjectCreated:*,s3:ObjectRemoved:*,s3:ObjectAccessed:*   Filter: suffix=".txt"
arn:minio:sqs:us-east-1:myinstance:mysql   s3:ObjectCreated:*   Filter: suffix=".txt"
$
$ **mc admin config reset myminio notify_mysql:myinstance**
Reseteting key has been successful.
Please restart your server with `mc admin service restart myminio`.

$ **mc admin config get myminio notify_mysql**
notify_mysql enable=off format=namespace host= port= username= password= database= dsn_string= table= queue_dir= queue_limit=0 
notify_mysql:myinstance format=namespace host=localhost port=3306 username=minio password=Minio123$ database=miniodb dsn_string= table=minio_table queue_dir= queue_limit=0 
$
$ **mc admin service restart myminio**
Restart command successfully sent to `myminio`.
Restarted `myminio` successfully.
$
$ **mc admin config get myminio notify_mysql**
notify_mysql enable=off format=namespace host= port= username= password= database= dsn_string= table= queue_dir= queue_limit=0 
$
$ **mc event list myminio/table**
mc: <ERROR> Cannot list notifications on the specified bucket. Get "http://192.168.1.26:9000/table/?notification=": Connection closed by foreign host http://192.168.1.26:9000/table/?notification=. Retry again.

Crash happens on the server side.
## mc --version
mc version DEVELOPMENT.2020-04-13T09-05-21Z
## System information
Server started on my local machine like:
`MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 MINIO_REGION="us-east-1" minio server <data-directory>`

**Comment by ebozduman** [comment]
## WorkAround:
The only way you can recover from this condition is to remove the notification.xml file,
$ **rm \<data-directory\>/.minio.sys/buckets/\<bucket-name\>/notification.xml**
and restart the server.
