### ISSUE TITLE
segmentation fault in mc admin decom status

### ISSUE THREAD

**Issue by haslersn** [minio/mc#4141]
When specifying a pool that doesn't exist, there's a segmentation fault:

```
$ mc admin decom status alias/ a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xd99262]

goroutine 1 [running]:
github.com/minio/mc/cmd.mainAdminDecommissionStatus(0xc0003c7a00)
	github.com/minio/mc/cmd/admin-decom-status.go:89 +0x402
github.com/minio/cli.HandleAction({0xf5da20?, 0x1181448?}, 0x6?)
	github.com/minio/cli@v1.22.0/app.go:498 +0x5a
github.com/minio/cli.Command.Run({{0x10efe40, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x111baff, 0x23}, {0x0, ...}, ...}, ...)
	github.com/minio/cli@v1.22.0/command.go:225 +0x9f7
github.com/minio/cli.(*App).RunAsSubcommand(0xc0003c7380, 0xc0003c71e0)
	github.com/minio/cli@v1.22.0/app.go:387 +0x85b
github.com/minio/cli.Command.startApp({{0x10f7918, 0xc}, {0x0, 0x0}, {0x19ca060, 0x1, 0x1}, {0x1122b28, 0x28}, {0x0, ...}, ...}, ...)
	github.com/minio/cli@v1.22.0/command.go:313 +0x689
github.com/minio/cli.Command.Run({{0x10f7918, 0xc}, {0x0, 0x0}, {0x19ca060, 0x1, 0x1}, {0x1122b28, 0x28}, {0x0, ...}, ...}, ...)
	github.com/minio/cli@v1.22.0/command.go:111 +0x418
github.com/minio/cli.(*App).RunAsSubcommand(0xc0003c6ea0, 0xc0005024e0)
	github.com/minio/cli@v1.22.0/app.go:387 +0x85b
github.com/minio/cli.Command.startApp({{0x10edaaa, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1101fc3, 0x14}, {0x0, ...}, ...}, ...)
	github.com/minio/cli@v1.22.0/command.go:313 +0x689
github.com/minio/cli.Command.Run({{0x10edaaa, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1101fc3, 0x14}, {0x0, ...}, ...}, ...)
	github.com/minio/cli@v1.22.0/command.go:111 +0x418
github.com/minio/cli.(*App).Run(0xc0005021a0, {0xc00012c120, 0x6, 0x6})
	github.com/minio/cli@v1.22.0/app.go:261 +0x847
github.com/minio/mc/cmd.Main({0xc00012c120?, 0x6, 0x6})
	github.com/minio/mc/cmd/main.go:137 +0x365
main.main()
	github.com/minio/mc/main.go:27 +0x2e
```

mc version RELEASE.2022-05-09T04-08-26Z

**Comment by harshavardhana** [comment]
@haslersn if you are planning to decommission a pool, make sure you are using the latest version. There were some issues in decom that we fixed during our testing, QA that could have led to unreadable objects.

**Comment by haslersn** [comment]
Update: I think the server returns an empty body together with HTTP code 400 and MinIO code XMinioAdminInvalidArgument. But the client doesn't check for the error and parses the empty body to `{ID:0 CmdLine: LastUpdate:0001-01-01 00:00:00 +0000 UTC Decommission:<nil>}`.

However, I think the client should nonetheless check for `nil`, so that even a malicious server cannot cause a segfault on the client.

**Comment by harshavardhana** [comment]
fixed in https://github.com/minio/madmin-go/commit/b58b1f4848d02c4d5ac8fcfb4644bae14bf33680 and updated the dep in mc in #4130
