### ISSUE TITLE
Panic on Decommission

### ISSUE THREAD

**Issue by cniackz** [minio/mc#4509]
## Expected behavior

There shouldn't be any panic.

## Actual behavior

```
┌─────┬─────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────┬──────────┐
2023-03-08T16:28:32.7206511Z │ ID  │ Pools                                                                                           │ Capacity                         │ Status   │
2023-03-08T16:28:32.7241688Z │ 1st │ https://storage-lite-pool-0-{0...3}.storage-lite-hl.tenant-lite.svc.cluster.local/export{0...1} │ 102 GiB (used) / 5.4 TiB (total) │ Draining │
2023-03-08T16:28:32.7276074Z │ 2nd │ https://storage-lite-pool-1-{0...3}.storage-lite-hl.tenant-lite.svc.cluster.local/export{0...1} │ 102 GiB (used) / 5.4 TiB (total) │ Active   │
2023-03-08T16:28:32.7283101Z └─────┴─────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────┴──────────┘
2023-03-08T16:28:32.7336470Z mc admin decommission status myminio/ https://storage-lite-pool-0-{0...3}.storage-lite-hl.tenant-lite.svc.cluster.local/export{0...1}
2023-03-08T16:28:33.0439626Z panic: runtime error: integer divide by zero
2023-03-08T16:28:33.0447842Z 
2023-03-08T16:28:33.0473695Z goroutine 1 [running]:
2023-03-08T16:28:33.0496653Z github.com/minio/mc/cmd.mainAdminDecommissionStatus(0xc00016c000)
2023-03-08T16:28:33.0530312Z 	github.com/minio/mc/cmd/admin-decom-status.go:102 +0xddb
2023-03-08T16:28:33.0585102Z github.com/minio/cli.HandleAction({0x10a38a0?, 0x130c4b0?}, 0x6?)
2023-03-08T16:28:33.0601787Z 	github.com/minio/cli@v1.24.2/app.go:490 +0x5a
2023-03-08T16:28:33.0623671Z github.com/minio/cli.Command.Run({{0x125e52f, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x128f011, 0x23}, {0x0, ...}, ...}, ...)
2023-03-08T16:28:33.0624059Z 	github.com/minio/cli@v1.24.2/command.go:242 +0x9b7
2023-03-08T16:28:33.0624408Z github.com/minio/cli.(*App).RunAsSubcommand(0xc000670540, 0xc0000071e0)
2023-03-08T16:28:33.0624727Z 	github.com/minio/cli@v1.24.2/app.go:380 +0x7bb
2023-03-08T16:28:33.0633937Z github.com/minio/cli.Command.startApp({{0x1266bbb, 0xc}, {0x0, 0x0}, {0x1c78e80, 0x1, 0x1}, {0x129714a, 0x28}, {0x0, ...}, ...}, ...)
2023-03-08T16:28:33.0634389Z 	github.com/minio/cli@v1.24.2/command.go:346 +0x6c9
2023-03-08T16:28:33.0634797Z github.com/minio/cli.Command.Run({{0x1266bbb, 0xc}, {0x0, 0x0}, {0x1c78e80, 0x1, 0x1}, {0x129714a, 0x28}, {0x0, ...}, ...}, ...)
2023-03-08T16:28:33.0635135Z 	github.com/minio/cli@v1.24.2/command.go:117 +0x438
2023-03-08T16:28:33.0635460Z github.com/minio/cli.(*App).RunAsSubcommand(0xc000670380, 0xc00042b860)
2023-03-08T16:28:33.0635789Z 	github.com/minio/cli@v1.24.2/app.go:380 +0x7bb
2023-03-08T16:28:33.0636128Z github.com/minio/cli.Command.startApp({{0x125bf0f, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x12723dd, 0x14}, {0x0, ...}, ...}, ...)
2023-03-08T16:28:33.0636456Z 	github.com/minio/cli@v1.24.2/command.go:346 +0x6c9
2023-03-08T16:28:33.0636784Z github.com/minio/cli.Command.Run({{0x125bf0f, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x12723dd, 0x14}, {0x0, ...}, ...}, ...)
2023-03-08T16:28:33.0637107Z 	github.com/minio/cli@v1.24.2/command.go:117 +0x438
2023-03-08T16:28:33.0637398Z github.com/minio/cli.(*App).Run(0xc0003d8700, {0xc00003e1e0, 0x6, 0x6})
2023-03-08T16:28:33.0637811Z 	github.com/minio/cli@v1.24.2/app.go:260 +0x827
2023-03-08T16:28:33.0638273Z github.com/minio/mc/cmd.Main({0xc00003e1e0?, 0x6, 0x6})
2023-03-08T16:28:33.0638590Z 	github.com/minio/mc/cmd/main.go:141 +0x3ec
2023-03-08T16:28:33.0638836Z main.main()
2023-03-08T16:28:33.0639092Z 	github.com/minio/mc/main.go:28 +0x32
2023-03-08T16:28:33.4623838Z ┌─────┬─────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────┬──────────┐
2023-03-08T16:28:33.4714930Z │ ID  │ Pools                                                                                           │ Capacity                         │ Status   │
2023-03-08T16:28:33.4756294Z │ 1st │ https://storage-lite-pool-0-{0...3}.storage-lite-hl.tenant-lite.svc.cluster.local/export{0...1} │ 102 GiB (used) / 5.4 TiB (total) │ Complete │
2023-03-08T16:28:33.4848952Z │ 2nd │ https://storage-lite-pool-1-{0...3}.storage-lite-hl.tenant-lite.svc.cluster.local/export{0...1} │ 102 GiB (used) / 5.4 TiB (total) │ Active   │
2023-03-08T16:28:33.4853095Z └─────┴─────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────┴──────────┘
```

## Steps to reproduce the behavior:

1. Create a Tenant with Kind
2. Deploy an Ubuntu Pod inside the cluster with latest mc version, we used [RELEASE.2023-02-28T00-12-59Z](https://github.com/minio/mc/releases/tag/RELEASE.2023-02-28T00-12-59Z)
3. Install latest Operator v4.5.8
4. Deploy a tenant with 2 pools
5. Put some data in the tenant
6. Decommission one of the Pools 
7. Ask for status and you will see it: `mc admin decommission status myminio/ https://storage-lite-pool-0-{0...3}.storage-lite-hl.tenant-lite.svc.cluster.local/export{0...1}`

## mc --version
- (paste output of `mc --version`)

```
RELEASE.2023-02-28T00-12-59Z
```

## System information:

Issue was found in our Self-hosted Runner in the Datacenter, it is an Ubuntu Virtual Machine:

```
root@vm-runner-1:~# uname -a
Linux vm-runner-1 5.4.0-1086-kvm #92-Ubuntu SMP Wed Jan 25 17:54:55 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
@cniackz can you paste the output of --json ?

**Comment by klauspost** [comment]
https://github.com/minio/mc/pull/4510
