### ISSUE TITLE
panic: unexpected size

### ISSUE THREAD

**Issue by USMortality** [minio/mc#4786]
## Expected behavior
Copy of a html file stored on s3 fails.

## Actual behavior
```
mc cp minio/data/index.html .                                       19:08:12
 0 B / ? ━┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉━━panic: unexpected size

goroutine 89 [running]:
github.com/minio/mc/cmd.(*ParallelManager).enoughMemForUpload(0xc0000520a0?, 0xffffffffffffffff?)
	github.com/minio/mc/cmd/parallel-manager.go:179 +0xc5
github.com/minio/mc/cmd.(*ParallelManager).doQueueTask(0xc0000520a0, {0xc0000dea00, 0x0, 0xffffffffffffffff})
	github.com/minio/mc/cmd/parallel-manager.go:210 +0x2d
github.com/minio/mc/cmd.(*ParallelManager).queueTask(...)
	github.com/minio/mc/cmd/parallel-manager.go:167
github.com/minio/mc/cmd.doCopySession.func3()
	github.com/minio/mc/cmd/cp-main.go:564 +0xb1a
created by github.com/minio/mc/cmd.doCopySession in goroutine 1
	github.com/minio/mc/cmd/cp-main.go:486 +0x888
```

## Steps to reproduce the behavior
mc cp minio/data/index.html .

Trying to download this file: https://s3.mortality.watch/charts/index.html

## mc --version
```
mc version RELEASE.2023-12-02T02-03-28Z (commit-id=f5f7147b9ec4cf78eb67f1cdc91b63d191852e6a)
Runtime: go1.21.4 darwin/amd64
Copyright (c) 2015-0000 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

## System information
Software:

    System Software Overview:

      System Version: macOS 14.1.2 (23B92)
      Kernel Version: Darwin 23.1.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3 days, 3 hours, 4 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,1
      Model Number: MK183LL/A
      Chip: Unknown
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 16 GB
      System Firmware Version: 10151.41.12
      OS Loader Version: 10151.41.12
      Activation Lock Status: Enabled
```

The same happens on Linux CI server.

Any ideas? Thx!

**Comment by harshavardhana** [comment]
We will check.

**Comment by klauspost** [comment]
Content Length is not being returned. Presumably the file is compressed, so AWS/Cloudflare removes the Content-Length

@vadmeste Similar to our previous discussion. We need to deal with this.
