### ISSUE TITLE
Panic on cp from play to fs on windows

### ISSUE THREAD

**Issue by fkautz** [minio/mc#790]
Ran on b308a5025fcaf96273f6694f4c86ff24760c4c02
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x538a59]

goroutine 8579 [running]:
github.com/minio/mc/pkg/client/s3.(*s3Client).Stat(0xc08221c260, 0x52, 0x0, 0x0)
        C:/Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3//Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3/
s3.go:158 +0x529
main.func┬╖013(0xc082465920, 0x52, 0xc082559140, 0x35, 0xc082465980)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-url.go:127 +0x131
created by main.prepareCopyURLsTypeA
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-url.go:154 +0x7f

goroutine 1 [chan receive, 2 minutes]:
main.runCopyCmd(0xc0820aa2d0)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cmd-cp.go:211 +0x751
github.com/minio/cli.Command.Run(0x83b310, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8d1170, 0x40, 0x0, ...)
        C:/Users/fkautz/go/src/github.com/minio/cli//Users/fkautz/go/src/github.com/minio/cli/command.go:123 +0x1074
github.com/minio/cli.(*App).Run(0xc08205c300, 0xc082006180, 0x4, 0x4, 0x0, 0x0)
        C:/Users/fkautz/go/src/github.com/minio/cli//Users/fkautz/go/src/github.com/minio/cli/app.go:189 +0x85d
github.com/minio/cli.(*App).RunAndExitOnError(0xc08205c300)
        C:/Users/fkautz/go/src/github.com/minio/cli//Users/fkautz/go/src/github.com/minio/cli/app.go:200 +0x53
main.main()
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/main.go:173 +0x13f2

goroutine 5 [chan receive]:
main.func┬╖012(0xc082093740, 0xc0820937a0)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-bar.go:140 +0x381
created by main.newCpBar
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-bar.go:174 +0x96

goroutine 6 [chan send]:
main.func┬╖003(0xc0820a10e0, 0x1, 0x2, 0xc082008220, 0x3, 0xc082093740, 0xc0820937a0, 0xc082093800)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cmd-cp.go:166 +0x39b
created by main.doCopyCmd
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cmd-cp.go:174 +0xa0

goroutine 7 [select]:
github.com/minio/mc/pkg/countlock.func┬╖001(0xc0820938c0, 0xc082093920, 0xc082093980)
        C:/Users/fkautz/go/src/github.com/minio/mc/pkg/countlock//Users/fkautz/go/src/github.com/minio/mc/pkg/countlock/
lock.go:58 +0x212
created by github.com/minio/mc/pkg/countlock.New
        C:/Users/fkautz/go/src/github.com/minio/mc/pkg/countlock//Users/fkautz/go/src/github.com/minio/mc/pkg/countlock/
lock.go:67 +0xc3

goroutine 8 [chan receive]:
main.func┬╖002(0xc0820a10e0, 0x1, 0x2, 0xc082008220, 0x3)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cmd-cp.go:142 +0xc0
created by main.func┬╖003
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cmd-cp.go:153 +0x1ea

goroutine 9 [chan receive]:
main.func┬╖017(0xc0820a10e0, 0x1, 0x2, 0xc082008220, 0x3, 0xc0820939e0)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-url.go:382 +0x3f2
created by main.prepareCopyURLs
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-url.go:392 +0x89

goroutine 10 [chan receive]:
main.func┬╖017(0xc0820a10e0, 0x1, 0x2, 0xc082008220, 0x3, 0xc082092000)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-url.go:382 +0x3f2
created by main.prepareCopyURLs
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-url.go:392 +0x89

goroutine 11 [runnable]:
main.func┬╖015(0xc0820a4390, 0x21, 0xc082008220, 0x3, 0xc082092060)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-url.go:312 +0x1215
created by main.prepareCopyURLsTypeC
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-url.go:317 +0x7f

goroutine 12 [chan receive]:
main.func┬╖015(0xc0820a4390, 0x21, 0xc082008220, 0x3, 0xc0820920c0)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-url.go:312 +0x1215
created by main.prepareCopyURLsTypeC
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-url.go:317 +0x7f

goroutine 28 [chan send]:
github.com/minio/mc/pkg/client/s3.(*s3Client).listRecursiveInRoutine(0xc08206b3e0, 0xc08202bc80)
        C:/Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3//Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3/
s3.go:351 +0x967
created by github.com/minio/mc/pkg/client/s3.(*s3Client).List
        C:/Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3//Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3/
s3.go:211 +0x72

goroutine 21 [chan send]:
github.com/minio/mc/pkg/client/s3.(*s3Client).listRecursiveInRoutine(0xc08206ac20, 0xc08202ad20)
        C:/Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3//Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3/
s3.go:351 +0x967
created by github.com/minio/mc/pkg/client/s3.(*s3Client).List
        C:/Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3//Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3/
s3.go:211 +0x72

goroutine 22 [chan send]:
github.com/minio/minio-go.api.listObjectsInRoutine(0xc082010a10, 0xc0820a43ab, 0x5, 0xc0820a43aa, 0x0, 0xc082244f01, 0xc
08202ad80)
        C:/Users/fkautz/go/src/github.com/minio/minio-go//Users/fkautz/go/src/github.com/minio/minio-go/api.go:619 +0x32
7
created by github.com/minio/minio-go.api.ListObjects
        C:/Users/fkautz/go/src/github.com/minio/minio-go//Users/fkautz/go/src/github.com/minio/minio-go/api.go:670 +0x9a


goroutine 29 [chan send]:
github.com/minio/minio-go.api.listObjectsInRoutine(0xc082011420, 0xc0820a43ab, 0x5, 0xc0820a43aa, 0x0, 0xc082266b01, 0xc
08202bce0)
        C:/Users/fkautz/go/src/github.com/minio/minio-go//Users/fkautz/go/src/github.com/minio/minio-go/api.go:619 +0x32
7
created by github.com/minio/minio-go.api.ListObjects
        C:/Users/fkautz/go/src/github.com/minio/minio-go//Users/fkautz/go/src/github.com/minio/minio-go/api.go:670 +0x9a


goroutine 8586 [select]:
net/http.(*Transport).getConn(0xc08202c090, 0xc082397040, 0x0, 0xc0824083f0, 0x5, 0xc0824083f8, 0x12, 0x0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:525 +0x60f
net/http.(*Transport).RoundTrip(0xc08202c090, 0xc082397040, 0x82f870, 0x0, 0x0)
        c:/go/src/net/http/transport.go:228 +0x4db
github.com/minio/minio-go.(*request).Do(0xc08242f9e0, 0xc08228079b, 0x0, 0x0)
        C:/Users/fkautz/go/src/github.com/minio/minio-go//Users/fkautz/go/src/github.com/minio/minio-go/lowlevelrequest.
go:116 +0xa9
github.com/minio/minio-go.lowLevelAPI.getPartialObject(0xc0824080e0, 0xc08228079b, 0x5, 0xc0822807a1, 0x3a, 0x0, 0x0, 0x
0, 0x0, 0x0, ...)
        C:/Users/fkautz/go/src/github.com/minio/minio-go//Users/fkautz/go/src/github.com/minio/minio-go/lowlevelapi.go:5
23 +0x1ea
github.com/minio/minio-go.api.GetPartialObject(0xc0824080e0, 0xc08228079b, 0x5, 0xc0822807a1, 0x3a, 0x0, 0x0, 0x0, 0x0,
0x0, ...)
        C:/Users/fkautz/go/src/github.com/minio/minio-go//Users/fkautz/go/src/github.com/minio/minio-go/api.go:218 +0xd2

github.com/minio/mc/pkg/client/s3.(*s3Client).GetObject(0xc08242f6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3//Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3/
s3.go:97 +0x102
main.getSource(0xc082280780, 0x5b, 0x0, 0x0, 0xc0822f5ec0, 0x0, 0x0)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/common-methods.go:38 +0x1ac
main.doCopy(0xc082381480, 0xc082552480, 0x0, 0x0, 0xc08206c780, 0x0, 0x0)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cmd-cp.go:78 +0x1ed
main.doCopyInRoutine(0xc082381480, 0xc082552480, 0x0, 0x0, 0xc08206c780, 0xc0820951f0, 0xc082093800, 0xc0820a1160)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cmd-cp.go:122 +0x6d
created by main.func┬╖003
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cmd-cp.go:171 +0x42f

goroutine 8590 [IO wait]:
net.(*pollDesc).Wait(0xc0820831f0, 0x77, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082046178, 0xc082083168, 0x84bf50, 0x9, 0x900138, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).connect(0xc082083080, 0x1727c8, 0xc082401840, 0x1727c8, 0xc082401820, 0xecd0da205, 0x3acfeccc, 0xa3ba40, 0x
0, 0x0)
        c:/go/src/net/fd_windows.go:361 +0x391
net.(*netFD).dial(0xc082083080, 0x172778, 0x0, 0x172778, 0xc082279b90, 0xecd0da205, 0x3acfeccc, 0xa3ba40, 0x0, 0x0)
        c:/go/src/net/sock_posix.go:139 +0x381
net.socket(0x842cd0, 0x3, 0x2, 0x1, 0x0, 0xc082279b00, 0x172778, 0x0, 0x172778, 0xc082279b90, ...)
        c:/go/src/net/sock_posix.go:91 +0x377
net.internetSocket(0x842cd0, 0x3, 0x172778, 0x0, 0x172778, 0xc082279b90, 0xecd0da205, 0x3acfeccc, 0xa3ba40, 0x1, ...)
        c:/go/src/net/ipsock_posix.go:137 +0x14f
net.dialTCP(0x842cd0, 0x3, 0x0, 0xc082279b90, 0xecd0da205, 0x3acfeccc, 0xa3ba40, 0x1, 0x0, 0x0)
        c:/go/src/net/tcpsock_posix.go:156 +0x12c
net.dialSingle(0x842cd0, 0x3, 0xc0823ec388, 0x12, 0x0, 0x0, 0x1726e8, 0xc082279b90, 0xecd0da205, 0x3acfeccc, ...)
        c:/go/src/net/dial.go:235 +0x3fc
net.func┬╖016(0xecd0da205, 0x3acfeccc, 0xa3ba40, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/net/dial.go:163 +0x133
net.dial(0x842cd0, 0x3, 0x1726e8, 0xc082279b90, 0xc082279bc0, 0xecd0da205, 0xe3acfeccc, 0xa3ba40, 0x0, 0x0, ...)
        c:/go/src/net/fd_windows.go:92 +0x122
net.(*Dialer).Dial(0xc082006140, 0x842cd0, 0x3, 0xc0823ec388, 0x12, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/net/dial.go:170 +0x6bc
net.*Dialer.Dial┬╖fm(0x842cd0, 0x3, 0xc0823ec388, 0x12, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:38 +0x80
net/http.(*Transport).dial(0xc08202c090, 0x842cd0, 0x3, 0xc0823ec388, 0x12, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:479 +0x8b
net/http.(*Transport).dialConn(0xc08202c090, 0x0, 0xc0823ec380, 0x5, 0xc0823ec388, 0x12, 0xc08246f6e0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:564 +0x167f
net/http.func┬╖019()
        c:/go/src/net/http/transport.go:520 +0x49
created by net/http.(*Transport).getConn
        c:/go/src/net/http/transport.go:522 +0x33c

goroutine 8587 [runnable]:
net.(*pollDesc).Wait(0xc0820828f0, 0x77, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082046178, 0xc082082868, 0x84bf50, 0x9, 0x900138, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).connect(0xc082082780, 0x1727c8, 0xc08242fb00, 0x1727c8, 0xc08242fae0, 0xecd0da205, 0x37b8d4e0, 0xa3ba40, 0x
0, 0x0)
        c:/go/src/net/fd_windows.go:361 +0x391
net.(*netFD).dial(0xc082082780, 0x172778, 0x0, 0x172778, 0xc082278690, 0xecd0da205, 0x37b8d4e0, 0xa3ba40, 0x0, 0x0)
        c:/go/src/net/sock_posix.go:139 +0x381
net.socket(0x842cd0, 0x3, 0x2, 0x1, 0x0, 0xc082278600, 0x172778, 0x0, 0x172778, 0xc082278690, ...)
        c:/go/src/net/sock_posix.go:91 +0x377
net.internetSocket(0x842cd0, 0x3, 0x172778, 0x0, 0x172778, 0xc082278690, 0xecd0da205, 0x37b8d4e0, 0xa3ba40, 0x1, ...)
        c:/go/src/net/ipsock_posix.go:137 +0x14f
net.dialTCP(0x842cd0, 0x3, 0x0, 0xc082278690, 0xecd0da205, 0x37b8d4e0, 0xa3ba40, 0x1, 0x0, 0x0)
        c:/go/src/net/tcpsock_posix.go:156 +0x12c
net.dialSingle(0x842cd0, 0x3, 0xc0824083f8, 0x12, 0x0, 0x0, 0x1726e8, 0xc082278690, 0xecd0da205, 0x37b8d4e0, ...)
        c:/go/src/net/dial.go:235 +0x3fc
net.func┬╖016(0xecd0da205, 0x37b8d4e0, 0xa3ba40, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/net/dial.go:163 +0x133
net.dial(0x842cd0, 0x3, 0x1726e8, 0xc082278690, 0xc0822786c0, 0xecd0da205, 0xe37b8d4e0, 0xa3ba40, 0x0, 0x0, ...)
        c:/go/src/net/fd_windows.go:92 +0x122
net.(*Dialer).Dial(0xc082006140, 0x842cd0, 0x3, 0xc0824083f8, 0x12, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/net/dial.go:170 +0x6bc
net.*Dialer.Dial┬╖fm(0x842cd0, 0x3, 0xc0824083f8, 0x12, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:38 +0x80
net/http.(*Transport).dial(0xc08202c090, 0x842cd0, 0x3, 0xc0824083f8, 0x12, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:479 +0x8b
net/http.(*Transport).dialConn(0xc08202c090, 0x0, 0xc0824083f0, 0x5, 0xc0824083f8, 0x12, 0xc082464ba0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:564 +0x167f
net/http.func┬╖019()
        c:/go/src/net/http/transport.go:520 +0x49
created by net/http.(*Transport).getConn
        c:/go/src/net/http/transport.go:522 +0x33c

goroutine 8589 [select]:
net/http.(*Transport).getConn(0xc08202c090, 0xc0823976c0, 0x0, 0xc0823ec380, 0x5, 0xc0823ec388, 0x12, 0x0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:525 +0x60f
net/http.(*Transport).RoundTrip(0xc08202c090, 0xc0823976c0, 0xc082279ad0, 0x0, 0x0)
        c:/go/src/net/http/transport.go:228 +0x4db
github.com/minio/minio-go.(*request).Do(0xc082401740, 0xc08233f87b, 0x0, 0x0)
        C:/Users/fkautz/go/src/github.com/minio/minio-go//Users/fkautz/go/src/github.com/minio/minio-go/lowlevelrequest.
go:116 +0xa9
github.com/minio/minio-go.lowLevelAPI.headObject(0xc0823ec070, 0xc08233f87b, 0x5, 0xc08233f881, 0x3a, 0x0, 0x0, 0x0, 0x0
, 0x0, ...)
        C:/Users/fkautz/go/src/github.com/minio/minio-go//Users/fkautz/go/src/github.com/minio/minio-go/lowlevelapi.go:6
35 +0x21a
github.com/minio/minio-go.api.StatObject(0xc0823ec070, 0xc08233f87b, 0x5, 0xc08233f881, 0x3a, 0x0, 0x0, 0x0, 0x0, 0x0, .
..)
        C:/Users/fkautz/go/src/github.com/minio/minio-go//Users/fkautz/go/src/github.com/minio/minio-go/api.go:475 +0xa0

github.com/minio/mc/pkg/client/s3.(*s3Client).Stat(0xc082401420, 0x5b, 0x0, 0x0)
        C:/Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3//Users/fkautz/go/src/github.com/minio/mc/pkg/client/s3/
s3.go:155 +0x2a9
main.func┬╖013(0xc08233f860, 0x5b, 0xc082546100, 0x3e, 0xc08233f8c0)
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-url.go:127 +0x131
created by main.prepareCopyURLsTypeA
        C:/Users/fkautz/go/src/github.com/minio/mc//Users/fkautz/go/src/github.com/minio/mc/cp-url.go:154 +0x7f

goroutine 81 [select]:
github.com/cheggaaa/pb.(*ProgressBar).writer(0xc08205ce00)
        C:/Users/fkautz/go/src/github.com/cheggaaa/pb//Users/fkautz/go/src/github.com/cheggaaa/pb/pb.go:351 +0x117
created by github.com/cheggaaa/pb.(*ProgressBar).Start
        C:/Users/fkautz/go/src/github.com/cheggaaa/pb//Users/fkautz/go/src/github.com/cheggaaa/pb/pb.go:104 +0xbd
```

**Comment by fkautz** [comment]
Fixed by #791.
